# Sample pd.DataFrame

In [1]:
# Importando as bibliotecas
import os
try:
    os.chdir("aulas_teoricas")
except FileNotFoundError:
    pass

from joblib import load, dump
import pandas as pd

In [2]:
# Importando o banco de dados
df_14 = load('./data/05_aula_df_14')

df_14.head()

,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max,target,linear_simples,linear_multi,svm,nb,NN
53,24.36,1,0,0,0,1,41,41.772154,42.144690,41,41,19.027222
93,8.05,0,1,0,1,0,9,17.536860,16.687991,9,23,18.997921
20,19.92,1,0,0,0,1,36,35.174686,35.667611,41,41,19.026806
177,7.73,1,0,1,0,0,13,17.061367,17.884818,9,17,18.994503
26,6.21,1,0,1,0,0,17,14.802774,15.667440,18,17,18.986990

In [3]:
# Importando
df_10 = load('./data/05_aula_df_10')

df_10.head()

,indep_1,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max,target,k_means,DBSCAN_1,DBSCAN_2,NN-DBSCAN_1,k_NN,log_reg,SVM,dec_tree,random_forest,gbm,nb,NN
53,41,24.36,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
93,9,8.05,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
20,36,19.92,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
177,13,7.73,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1
26,17,6.21,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1

In [4]:
def train_valid_test_df_split(
        df: pd.DataFrame,
        indep: list,
        target: str = "target",
        frac_valid: float = 0.2,
        frac_test: float = 0.13) -> tuple:
    '''
    Função que divide o DataFrame em treino, teste e validação
    e separa as colunas independentes e a coluna alvo.
    Esta função divide o DataFrame em três partes: treino, teste e validação,
    e separa as colunas independentes e a coluna alvo.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame a ser dividido.
    indep : list
        Lista de colunas independentes.
    target : str, optional
        Nome da coluna alvo. Default é "target".
    frac_valid : float, optional
        Proporção do DataFrame a ser usado como validação. Default é 0.2.
    frac_test : float, optional
        Proporção do DataFrame a ser usado como teste. Default é 0.13.
    
    Returns
    -------
    tuple
        Retorna uma tupla contendo:
        - df_train: DataFrame de treino.
        - df_valid: DataFrame de validação.
        - df_test: DataFrame de teste.
        - X_train: DataFrame de treino com colunas independentes.
        - X_valid: DataFrame de validação com colunas independentes.
        - X_test: DataFrame de teste com colunas independentes.
        - y_train: Série alvo de treino.
        - y_valid: Série alvo de validação.
        - y_test: Série alvo de teste.
    '''
    index = df.sample(frac=frac_valid, random_state=42).index
    df_train = df.loc[[i for i in df.index if i not in index], :]
    df_valid = df.loc[index, :]

    index = df_train.sample(frac=frac_test, random_state=42).index
    df_train = df_10.loc[[i for i in df_train.index if i not in index], :]
    df_test = df_10.loc[index, :]

    X_train = df_train.loc[:, indep].copy()
    X_valid = df_valid.loc[:, indep].copy()
    X_test = df_test.loc[:, indep].copy()

    y_train = df_train.loc[:, target].copy()
    y_valid = df_valid.loc[:, target].copy()
    y_test = df_test.loc[:, target].copy()

    linha = "-"*10
    print(linha)
    print(f"df_train: {df_train.shape}")
    print(f"df_valid: {df_valid.shape}")
    print(f"df_test: {df_test.shape}")

    print(linha)
    print(f"X_train: {X_train.shape}")
    print(f"X_valid: {X_valid.shape}")
    print(f"X_test: {X_test.shape}")

    print(linha)
    print(f"y_train: {y_train.shape}")
    print(f"y_valid: {y_valid.shape}")
    print(f"y_test: {y_test.shape}")

    print(linha)
    print(f"Train: {df_train.shape[0]/df_10.shape[0]:.0%}")
    print(f"Valid: {df_valid.shape[0]/df_10.shape[0]:.0%}")
    print(f"Test: {df_test.shape[0]/df_10.shape[0]:.0%}")

    return (
        df_train,
        df_valid,
        df_test,
        X_train,
        X_valid,
        X_test,
        y_train,
        y_valid,
        y_test
    )

In [5]:
df_10.columns[[0, 1, 2, 3, 4, 5, 6]]

Index(['indep_1', 'indep_2', 'indep_3_max', 'indep_3_min', 'indep_4_min',
       'indep_4_med', 'indep_4_max'],
      dtype='object')

In [6]:
indep = df_10.columns[[0, 1, 2, 3, 4, 5, 6]]
df_10_train, df_10_test, df_10_valid, X_test, X_train, X_valid, y_test, y_train, y_valid = train_valid_test_df_split(df=df_10, indep=indep)

----------
df_train: (70, 20)
df_valid: (20, 20)
df_test: (10, 20)
----------
X_train: (70, 7)
X_valid: (20, 7)
X_test: (10, 7)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)
----------
Train: 70%
Valid: 20%
Test: 10%

In [7]:
X_test.head()

,indep_1,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max
20,36,19.92,1,0,0,0,1
177,13,7.73,1,0,1,0,0
0,21,6.37,0,1,1,0,0
21,31,12.16,1,0,0,1,0
179,16,7.68,1,0,1,0,0

In [8]:
y_test.head()

20     0
177    1
0      1
21     0
179    1
Name: target, dtype: int64

# Sample Sklearn

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = df_10[indep]
y = df_10['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_test, X_valid, y_test, y_valid = train_test_split(X_test, y_test, test_size=0.66, random_state=42)

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (70, 7)
X_valid: (20, 7)
X_test: (10, 7)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)

# Sample fast_ml

In [11]:
!pip freeze | grep fast

fast-ml==3.68
fastjsonschema==2.21.2

In [12]:
from fast_ml.model_development import train_valid_test_split

In [13]:
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(
    df_10,
    target='target', 
    train_size=0.7, 
    valid_size=0.2, 
    test_size=0.1, 
    random_state=42
)

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (70, 19)
X_valid: (20, 19)
X_test: (10, 19)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)

In [14]:
X_train.head()

,indep_1,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max,k_means,DBSCAN_1,DBSCAN_2,NN-DBSCAN_1,k_NN,log_reg,SVM,dec_tree,random_forest,gbm,nb,NN
30,20,6.06,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
161,35,21.02,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
176,13,7.95,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1
109,32,21.84,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
150,26,13.54,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1

In [15]:
y_train.head()

30     1
161    0
176    1
109    0
150    1
Name: target, dtype: int64

# Sample Numpy

In [16]:
import numpy as np

In [17]:
train_size = int(len(df_10)*.4)
test_size = int(len(df_10)*.1)

print(f"Train size: {train_size}")
print(f"Test size: {test_size}")

Train size: 40
Test size: 10

In [18]:
train_size = int(len(df_10)*.22)
test_size = int(len(df_10)*.10)

target = 'target'
index = np.random.choice(df_10.index, size=train_size, replace=False)
df_train = df_10.loc[[i for i in df_10.index if i not in index], :]
df_valid = df_10.loc[index, :]

index = np.random.choice(df_10.index, size=test_size, replace=False)
df_train = df_10.loc[[i for i in df_train.index if i not in index], :]
df_test = df_10.loc[index, :]

X_train = df_train.loc[:, indep].copy()
X_valid = df_valid.loc[:, indep].copy()
X_test = df_test.loc[:, indep].copy()

y_train = df_train.loc[:, target].copy()
y_valid = df_valid.loc[:, target].copy()
y_test = df_test.loc[:, target].copy()

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (71, 7)
X_valid: (22, 7)
X_test: (10, 7)
----------
y_train: (71,)
y_valid: (22,)
y_test: (10,)

# Novas DataFrames

In [19]:
df_biomarc = load('./data/06_aula_df_biomarc')

df_biomarc.head()

,CD34,TdT,MPO,CD19_1,CD20_1,CD22,CD3_1,CD7,BCR-ABL,PML-RARA,...,IgA_2,IgM,CD16,CD56,DHR,CH50,C3,C4,FOXP3,classe
0,0.119362,True,True,0.471228,0.398837,0.233216,0.329756,0.417118,True,True,...,Alto,Alto,247.894093,396.067195,0.967908,93.066630,230.919871,42.436133,Normal,leucemia
1,0.112420,True,True,0.292042,0.370941,0.253135,0.340733,0.350616,True,True,...,Alto,Alto,213.416161,361.036864,0.972741,135.639268,351.466206,64.065366,Normal,leucemia
2,0.175636,True,True,0.372872,0.257518,0.451758,0.487803,0.399385,True,True,...,Alto,Alto,296.635039,244.867766,0.971384,69.452609,238.588931,44.199585,Normal,leucemia
3,0.078518,True,True,0.469943,0.495637,0.351360,0.332752,0.487439,True,True,...,Alto,Alto,564.401375,530.296010,0.962450,90.100424,262.826983,41.494853,Normal,leucemia
4,0.061083,True,True,0.349343,0.381742,0.220939,0.479723,0.453555,True,True,...,Alto,Alto,238.791009,152.442218,0.955740,76.029046,209.943682,46.315645,Normal,leucemia

In [20]:
df_biomarc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 260
Data columns (total 38 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CD34      1000 non-null   float64
 1   TdT       1000 non-null   bool
 2   MPO       1000 non-null   bool
 3   CD19_1    1000 non-null   float64
 4   CD20_1    1000 non-null   float64
 5   CD22      1000 non-null   float64
 6   CD3_1     1000 non-null   float64
 7   CD7       1000 non-null   float64
 8   BCR-ABL   1000 non-null   bool
 9   PML-RARA  1000 non-null   bool
 10  NMP22     1000 non-null   float64
 11  BTA       1000 non-null   bool
 12  hTERT     1000 non-null   bool
 13  uCyt+     1000 non-null   bool
 14  FGFR3     1000 non-null   category
 15  TP53      1000 non-null   float64
 16  PPD       1000 non-null   float64
 17  IFN-γ     1000 non-null   float64
 18  IL-2      1000 non-null   category
 19  TNF-α     1000 non-null   category
 20  Th1       1000 non-null   float64
 21  IgG_1     1000 non-null   category
 22  IgA_1     1000 non-null   category
 23  CD3_2     1000 non-null   float64
 24  CD4       1000 non-null   float64
 25  CD8       1000 non-null   float64
 26  CD19_2    1000 non-null   float64
 27  CD20_2    1000 non-null   float64
 28  IgA_2     1000 non-null   category
 29  IgM       1000 non-null   category
 30  CD16      1000 non-null   float64
 31  CD56      1000 non-null   float64
 32  DHR       1000 non-null   float64
 33  CH50      1000 non-null   float64
 34  C3        1000 non-null   float64
 35  C4        1000 non-null   float64
 36  FOXP3     1000 non-null   category
 37  classe    1000 non-null   object
dtypes: bool(7), category(8), float64(22), object(1)
memory usage: 202.3+ KB

In [21]:
df_variaveis = load('./data/06_aula_df_variaveis')

df_variaveis.head()

   num_cont num_disc      cat_nomi cat_ordi
0  1.993428      3.0  anhalouidine     midi
1  0.723471      2.0          joke     maxi
2  2.295377      1.0   orthobiosis     maxi
3  4.046060     -1.0      takedown    micro
4  0.531693      2.0     becrimson     midi

In [22]:
df_variaveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   num_cont  970 non-null    float64
 1   num_disc  1000 non-null   object
 2   cat_nomi  1000 non-null   object
 3   cat_ordi  1000 non-null   object
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

In [23]:
df_cells = load('./data/06_aula_df_cells')

df_cells.head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [24]:
df_cells.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 91
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sample     1000 non-null   object
 1   DV1 BR90   1000 non-null   float64
 2   DV2 265    1000 non-null   float64
 3   DV3 98     1000 non-null   float64
 4   DV4 360    1000 non-null   float64
 5   Cells      1000 non-null   object
 6   Treatment  1000 non-null   object
dtypes: float64(4), object(3)
memory usage: 62.5+ KB